-- 1. Tabel Profil Pendonor (donors)
CREATE TABLE IF NOT EXISTS donors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  blood_type TEXT DEFAULT 'O-',
  dob DATE DEFAULT '1995-07-15',
  phone TEXT DEFAULT '081357924680',
  address TEXT DEFAULT 'Jl. Raya Darmo No. 45, Surabaya',
  total_donations INT DEFAULT 9,
  last_donation DATE DEFAULT '2025-10-22',
  next_eligible DATE DEFAULT '2026-01-22',
  points INT DEFAULT 350,
  level TEXT DEFAULT 'Veteran',
  streak INT DEFAULT 4,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabel Riwayat Donasi (donation_history)
CREATE TABLE IF NOT EXISTS donation_history (
  id TEXT PRIMARY KEY,
  donor_email TEXT NOT NULL,
  date DATE NOT NULL,
  location TEXT NOT NULL,
  blood_type TEXT NOT NULL,
  volume INT DEFAULT 450,
  points_earned INT DEFAULT 50,
  certificate BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabel Event Donor Darah (events)
CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  organizer TEXT DEFAULT 'PMI Kota Surabaya',
  date DATE NOT NULL,
  time TEXT DEFAULT '08:00 - 14:00',
  location TEXT NOT NULL,
  address TEXT NOT NULL,
  capacity INT DEFAULT 100,
  registered INT DEFAULT 0,
  description TEXT DEFAULT '',
  requirements TEXT DEFAULT 'Sehat jasmani, BB >= 45kg, Usia 17-60 tahun',
  status TEXT DEFAULT 'upcoming',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Tabel Pendaftaran Event (event_bookings)
CREATE TABLE IF NOT EXISTS event_bookings (
  id TEXT PRIMARY KEY,
  event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
  donor_name TEXT NOT NULL,
  donor_email TEXT NOT NULL,
  blood_type TEXT DEFAULT 'O-',
  qr_code TEXT NOT NULL,
  checked_in BOOLEAN DEFAULT false,
  registered_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Tabel Stok Darah Rumah Sakit (hospital_blood_stock)
CREATE TABLE IF NOT EXISTS hospital_blood_stock (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hospital_name TEXT NOT NULL,
  address TEXT NOT NULL,
  district TEXT NOT NULL,
  distance NUMERIC(4,1) DEFAULT 1.0,
  phone TEXT NOT NULL,
  blood_type TEXT NOT NULL,
  stock INT DEFAULT 0,
  status TEXT DEFAULT 'available',
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Tabel Stok Darah PMI (pmi_blood_stock)
CREATE TABLE IF NOT EXISTS pmi_blood_stock (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pmi_name TEXT NOT NULL,
  blood_type TEXT NOT NULL,
  stock INT DEFAULT 0,
  target INT DEFAULT 20,
  status TEXT DEFAULT 'good',
  expiring_soon INT DEFAULT 0,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Tabel Permintaan Darah RS -> PMI (blood_requests)
CREATE TABLE IF NOT EXISTS blood_requests (
  id TEXT PRIMARY KEY,
  hospital TEXT NOT NULL,
  blood_type TEXT NOT NULL,
  qty INT NOT NULL,
  priority TEXT DEFAULT 'normal',
  status TEXT DEFAULT 'pending',
  time_ago TEXT DEFAULT 'Baru saja',
  address TEXT DEFAULT '',
  contact TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Tabel Pesanan Darah (blood_orders)
CREATE TABLE IF NOT EXISTS blood_orders (
  id TEXT PRIMARY KEY,
  blood_type TEXT NOT NULL,
  qty INT NOT NULL,
  urgency TEXT DEFAULT 'normal',
  status TEXT DEFAULT 'menunggu',
  pmi TEXT DEFAULT 'PMI Kota Surabaya',
  driver TEXT,
  eta TEXT,
  tracking_pct INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Tabel Pengiriman / Driver (deliveries)
CREATE TABLE IF NOT EXISTS deliveries (
  id TEXT PRIMARY KEY,
  order_id TEXT NOT NULL,
  blood_type TEXT NOT NULL,
  qty INT NOT NULL,
  from_location TEXT NOT NULL,
  to_location TEXT NOT NULL,
  driver TEXT NOT NULL,
  driver_phone TEXT DEFAULT '',
  status TEXT DEFAULT 'disiapkan',
  eta TEXT DEFAULT '15 mnt',
  distance TEXT DEFAULT '3 km',
  pct INT DEFAULT 0,
  urgent BOOLEAN DEFAULT false,
  from_lat NUMERIC(9,6) DEFAULT -7.2657,
  from_lng NUMERIC(9,6) DEFAULT 112.7445,
  to_lat NUMERIC(9,6) DEFAULT -7.2678,
  to_lng NUMERIC(9,6) DEFAULT 112.7584,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. Tabel Reward (rewards)
CREATE TABLE IF NOT EXISTS rewards (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  points INT DEFAULT 500,
  category TEXT DEFAULT 'voucher',
  icon TEXT DEFAULT '🎁',
  available BOOLEAN DEFAULT true,
  limited BOOLEAN DEFAULT false,
  limit_count INT DEFAULT 0
);

-- 11. Tabel Log Aktivitas (activity_logs)
CREATE TABLE IF NOT EXISTS activity_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action TEXT NOT NULL,
  blood_type TEXT NOT NULL,
  quantity INT NOT NULL,
  user_name TEXT NOT NULL,
  time_ago TEXT DEFAULT 'Baru saja',
  positive BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ====================================================================
-- SEED DATA AWAL (DATA CONTOH)
-- ====================================================================

INSERT INTO donors (email, name, blood_type, dob, phone, address, total_donations, points, level, streak)
VALUES ('rizky@gmail.com', 'Rizky Pratama', 'O-', '1995-07-15', '081357924680', 'Jl. Raya Darmo No. 45, Surabaya', 9, 350, 'Veteran', 4)
ON CONFLICT (email) DO NOTHING;

INSERT INTO donation_history (id, donor_email, date, location, blood_type, volume, points_earned, certificate)
VALUES
  ('D001', 'rizky@gmail.com', '2025-10-22', 'PMI Kota Surabaya', 'O-', 450, 50, true),
  ('D002', 'rizky@gmail.com', '2025-07-10', 'Event Donor Unair', 'O-', 450, 50, true),
  ('D003', 'rizky@gmail.com', '2025-04-05', 'PMI Surabaya Selatan', 'O-', 450, 50, false)
ON CONFLICT (id) DO NOTHING;

INSERT INTO events (id, name, organizer, date, time, location, address, capacity, registered, description, status)
VALUES
  (1, 'Donor Darah Peduli Surabaya 2026', 'PMI Kota Surabaya', '2026-07-15', '08:00 - 14:00', 'Mall Galaxy Surabaya', 'Jl. Dharmahusada Indah Timur No. 35', 150, 42, 'Kampanye donor darah rutin PMI Surabaya untuk memenuhi stok kantong darah.', 'upcoming'),
  (2, 'Event Donor Bersama UNAIR', 'KSR PMI Unair', '2026-08-01', '07:30 - 13:00', 'Kampus B Unair', 'Jl. Prof. Dr. Moestopo 47', 200, 89, 'Donor darah sosial dalam rangka Dies Natalis Unair.', 'upcoming'),
  (3, 'Donor Darah Pahlawan Kemanusiaan', 'PMI Surabaya Selatan', '2026-08-17', '09:00 - 15:00', 'Balai Kota Surabaya', 'Jl. Sedap Malam No. 1', 300, 120, 'Aksi donor darah memperingati Hari Kemerdekaan.', 'upcoming')
ON CONFLICT (id) DO NOTHING;

INSERT INTO hospital_blood_stock (hospital_name, address, district, distance, phone, blood_type, stock, status)
VALUES
  ('RSUD Dr. Soetomo', 'Jl. Mayjen Prof. Dr. Moestopo 6-8', 'Gubeng', 1.2, '(031) 501-0000', 'A+', 42, 'available'),
  ('RSUD Dr. Soetomo', 'Jl. Mayjen Prof. Dr. Moestopo 6-8', 'Gubeng', 1.2, '(031) 501-0000', 'B+', 8, 'low'),
  ('RSUD Dr. Soetomo', 'Jl. Mayjen Prof. Dr. Moestopo 6-8', 'Gubeng', 1.2, '(031) 501-0000', 'O+', 55, 'available'),
  ('RSUD Dr. Soetomo', 'Jl. Mayjen Prof. Dr. Moestopo 6-8', 'Gubeng', 1.2, '(031) 501-0000', 'AB+', 3, 'critical'),
  ('RS Siloam Surabaya', 'Jl. Raya Gubeng 70', 'Gubeng', 2.1, '(031) 505-7777', 'A+', 18, 'available'),
  ('RS Siloam Surabaya', 'Jl. Raya Gubeng 70', 'Gubeng', 2.1, '(031) 505-7777', 'B-', 5, 'low'),
  ('RS Siloam Surabaya', 'Jl. Raya Gubeng 70', 'Gubeng', 2.1, '(031) 505-7777', 'O-', 12, 'available'),
  ('RS Premier Surabaya', 'Jl. Nginden Intan Barat 10', 'Sukolilo', 3.8, '(031) 5999-999', 'B+', 30, 'available'),
  ('RS Premier Surabaya', 'Jl. Nginden Intan Barat 10', 'Sukolilo', 3.8, '(031) 5999-999', 'O+', 6, 'low')
ON CONFLICT DO NOTHING;

INSERT INTO pmi_blood_stock (pmi_name, blood_type, stock, target, status, expiring_soon)
VALUES
  ('PMI Kota Surabaya', 'A+', 48, 60, 'good', 2),
  ('PMI Kota Surabaya', 'A-', 8, 15, 'critical', 1),
  ('PMI Kota Surabaya', 'B+', 52, 60, 'good', 0),
  ('PMI Kota Surabaya', 'B-', 12, 20, 'low', 0),
  ('PMI Kota Surabaya', 'AB+', 18, 30, 'good', 1),
  ('PMI Kota Surabaya', 'AB-', 6, 10, 'low', 0),
  ('PMI Kota Surabaya', 'O+', 55, 70, 'good', 3),
  ('PMI Kota Surabaya', 'O-', 14, 30, 'low', 1)
ON CONFLICT DO NOTHING;

INSERT INTO blood_requests (id, hospital, blood_type, qty, priority, status, time_ago, address, contact)
VALUES
  ('REQ001', 'RSUD Dr. Soetomo', 'O+', 5, 'darurat', 'pending', '2 menit lalu', 'Jl. Mayjend Prof. Dr. Moestopo', '031-5501011'),
  ('REQ002', 'RS Siloam Surabaya', 'A-', 3, 'mendesak', 'diproses', '15 menit lalu', 'Jl. Gubeng Pojok 1', '031-5040955'),
  ('REQ003', 'RS Premier Surabaya', 'O-', 4, 'darurat', 'pending', '5 menit lalu', 'Jl. Nginden Intan Barat', '031-5993211')
ON CONFLICT (id) DO NOTHING;

INSERT INTO blood_orders (id, blood_type, qty, urgency, status, pmi, driver, eta, tracking_pct)
VALUES
  ('ORD001', 'O+', 5, 'darurat', 'dikirim', 'PMI Kota Surabaya', 'Budi Santoso (081234567890)', '5 mnt lagi', 75),
  ('ORD002', 'A-', 3, 'mendesak', 'diproses', 'PMI Surabaya Timur', 'Agus Prasetyo (082198765432)', '18 mnt lagi', 30),
  ('ORD003', 'B+', 8, 'normal', 'selesai', 'PMI Kota Surabaya', 'Hendra Wijaya', 'Sudah Tiba', 100)
ON CONFLICT (id) DO NOTHING;

INSERT INTO deliveries (id, order_id, blood_type, qty, from_location, to_location, driver, driver_phone, status, eta, distance, pct, urgent)
VALUES
  ('DEL001', 'ORD001', 'O+', 5, 'PMI Kota Surabaya', 'RSUD Dr. Soetomo', 'Budi Santoso', '081234567890', 'perjalanan', '6 mnt', '2.1 km', 72, true),
  ('DEL002', 'ORD002', 'A-', 3, 'PMI Surabaya Timur', 'RS Siloam Surabaya', 'Agus Prasetyo', '082198765432', 'dijemput', '18 mnt', '5.4 km', 25, false),
  ('DEL003', 'ORD003', 'B+', 8, 'PMI Kota Surabaya', 'RS Premier Surabaya', 'Hendra Wijaya', '083147852369', 'tiba', 'Sudah tiba', '3.8 km', 100, false)
ON CONFLICT (id) DO NOTHING;

INSERT INTO rewards (id, name, description, points, category, icon, available, limited, limit_count)
VALUES
  ('R001', 'Voucher Indomaret 25K', 'Tukar poin untuk voucher belanja Indomaret', 500, 'voucher', '🛒', true, false, 0),
  ('R002', 'Voucher GoPay 50K', 'Saldo GoPay langsung ke akunmu', 900, 'voucher', '💚', true, false, 0),
  ('R003', 'Sertifikat Donor Digital', 'Sertifikat resmi PMI dengan QR verifikasi', 0, 'sertifikat', '📜', true, false, 0),
  ('R004', 'Pin Enamel Pahlawan Darah', 'Pin eksklusif koleksi terbatas', 1200, 'merchandise', '📌', true, true, 50),
  ('R005', 'Kaos PMI Surabaya', 'Kaos katun premium edisi terbatas', 2000, 'merchandise', '👕', false, true, 20),
  ('R006', 'Diskon Lab Medis 15%', 'Diskon pemeriksaan kesehatan di lab mitra', 800, 'privilege', '🏥', true, false, 0),
  ('R007', 'Priority Event Booking', 'Daftar event 24 jam lebih awal dari publik', 300, 'privilege', '⭐', true, false, 0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO activity_logs (action, blood_type, quantity, user_name, time_ago, positive)
VALUES
  ('Pengisian Stok', 'O+', 15, 'Admin RS', '10 menit lalu', true),
  ('Pengeluaran Transfusi', 'A+', 3, 'Dr. Ahmad', '25 menit lalu', false),
  ('Penerimaan dari PMI', 'B+', 8, 'Admin RS', '1 jam lalu', true)
ON CONFLICT DO NOTHING;
