#!/bin/bash
# scripts/security-audit.sh
# Script audit keamanan otomatis

echo "🔒 Starting Security Audit for Bloodlink..."

# 1. Check for vulnerabilities in dependencies
echo "📦 Checking dependencies for vulnerabilities..."
pnpm audit --audit-level high --json > security-reports/audit-report.json

# 2. Check for exposed environment variables
echo "🔑 Checking for exposed environment variables..."
grep -r "process.env." src/ --include="*.ts" --include="*.tsx" > security-reports/env-usage.txt
grep -r "import.meta.env." src/ --include="*.ts" --include="*.tsx" >> security-reports/env-usage.txt

# 3. Check for dangerous React patterns
echo "⚛️ Scanning React code for security issues..."
grep -r "dangerouslySetInnerHTML" src/ --include="*.tsx" > security-reports/react-dangerous.txt
grep -r "eval(" src/ --include="*.ts" --include="*.tsx" >> security-reports/react-dangerous.txt

# 4. Check for hardcoded credentials
echo "🔐 Scanning for hardcoded credentials..."
grep -r "password\|secret\|key\|token" src/ --include="*.ts" --include="*.tsx" --exclude="*.test.ts" > security-reports/hardcoded-creds.txt

# 5. Check for SQL injection patterns
echo "💉 Scanning for SQL injection patterns..."
grep -r "supabase.rpc" src/ --include="*.ts" --include="*.tsx" > security-reports/rpc-usage.txt
grep -r "raw.*SQL" src/ --include="*.ts" --include="*.tsx" >> security-reports/rpc-usage.txt

# 6. Check for insecure HTTP requests
echo "🌐 Scanning for insecure HTTP requests..."
grep -r "http://" src/ --include="*.ts" --include="*.tsx" > security-reports/http-requests.txt

# 7. Check for missing security headers in vercel.json
echo "📋 Checking vercel.json security headers..."
if grep -q "Strict-Transport-Security" vercel.json; then
  echo "✅ HSTS header is present"
else
  echo "❌ HSTS header is missing"
fi

# 8. Generate security report
echo "📊 Generating security report..."
cat > security-reports/security-report.txt << EOF
========================================
   BLOODLINK SECURITY AUDIT REPORT
========================================
Date: $(date)
Generated by: Security Audit Script

1. DEPENDENCIES
   - Audit findings: $(cat security-reports/audit-report.json | jq '.metadata.vulnerabilities.total' || echo "N/A")

2. ENVIRONMENT VARIABLES
   - Files with env usage: $(cat security-reports/env-usage.txt | wc -l)

3. REACT SECURITY
   - dangerousSetInnerHTML usage: $(cat security-reports/react-dangerous.txt | wc -l)

4. HARDCODED CREDENTIALS
   - Suspicious files: $(cat security-reports/hardcoded-creds.txt | wc -l)

5. SQL INJECTION
   - RPC usage occurrences: $(cat security-reports/rpc-usage.txt | wc -l)

6. HTTP REQUESTS
   - Insecure HTTP usage: $(cat security-reports/http-requests.txt | wc -l)

========================================
   RECOMMENDATIONS
========================================
$(cat security-reports/summary.txt 2>/dev/null || echo "Run detailed analysis for recommendations")
EOF

echo "✅ Security audit complete! Report saved to security-reports/security-report.txt"